### GET /
GET http://localhost:5000

### Register a user POST /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123123123"
}


### Login a user POST /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /TODOS
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDA3NTIxLCJleHAiOjE3NDA0OTM5MjF9.PfIjzSyEUXJdnhM6Br0ZRWnMnxkR0oowkRSgF6ojr4s


###Creates a new todos POST /TODOS
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDA3NTIxLCJleHAiOjE3NDA0OTM5MjF9.PfIjzSyEUXJdnhM6Br0ZRWnMnxkR0oowkRSgF6ojr4s
Content-Type: application/json

{
    "task": "Finish coding the projects"
}