### GET /
GET http://localhost:5000

### Register a user POST /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123123123"
}


### Login a user POST /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /TODOS
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDE3MDQxLCJleHAiOjE3NDA1MDM0NDF9.dN_mPBZ1sjjnHjqqMunlKKyvvVU8iILjRHrODJ1ZPHU

###Creates a new todos POST /TODOS
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQwNDE3MDQxLCJleHAiOjE3NDA1MDM0NDF9.dN_mPBZ1sjjnHjqqMunlKKyvvVU8iILjRHrODJ1ZPHU

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID
PUT http://localhost:5000/todos/2
Authorization: 

Content-Type: application/json