### GET / 
GET http://localhost:5000

### Register a user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123456789"
}

### Login in a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "babucarr@gmail.com",
    "password": "123456789"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNzE3MTU3LCJleHAiOjE3NDE4MDM1NTd9._KXAidbAkhs7MhEWT2-oj2hA7CcqiEBqWEd2XVH56uU

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNzE3MTU3LCJleHAiOjE3NDE4MDM1NTd9._KXAidbAkhs7MhEWT2-oj2hA7CcqiEBqWEd2XVH56uU
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxNzE3MTU3LCJleHAiOjE3NDE4MDM1NTd9._KXAidbAkhs7MhEWT2-oj2hA7CcqiEBqWEd2XVH56uU
Content-Type: application/json